version: '3.8'
services:
  stats-server:
    build: ./stat/stats-server
    image: stat
    container_name: stats_server
    ports:
      - "9090:9090"
    depends_on:
    - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-db:
    image: postgres:15.2-alpine
    container_name: statDB
    ports:
      - "6590:5432"
    environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=12345

  ewm-service:
    build: ./main
    image: ewm-service
    container_name: ewm_container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - STATS-SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
