version: '3.8'
services:
  stats-server:
    build: ./stat/stats-server
    image: stat
    container_name: stats_server
    ports:
      - "9090:9090"
    depends_on:
    - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-db:
    image: postgres:15.2-alpine
    container_name: statDB
    ports:
      - "6590:5432"
    environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=12345
#
#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
